name: Sync Puzzles to Supabase

on:
  push:
    branches: [ main, master ]
    paths:
      - 'thenoonlight-app/puzzles/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-puzzles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
        cache-dependency-path: 'thenoonlight-app/pnpm-lock.yaml'
        
    - name: Install pnpm
      run: npm install -g pnpm
      
    - name: Install dependencies
      working-directory: ./thenoonlight-app
      run: pnpm install
      
    - name: Debug environment
      run: |
        echo "Current directory: $(pwd)"
        echo "Repository contents:"
        ls -la
        echo "Checking for thenoonlight-app directory:"
        ls -la thenoonlight-app/ || echo "thenoonlight-app directory not found"
      
    - name: List puzzle files
      working-directory: ./thenoonlight-app
      run: |
        echo "Puzzle files found:"
        find puzzles -name "*.json" -o -name "*.zip" | head -20
        echo "Puzzle directories:"
        ls -la puzzles/
      
    - name: Validate puzzles
      working-directory: ./thenoonlight-app
      run: pnpm run validate-puzzles
      
    - name: Sync puzzles to Supabase
      working-directory: ./thenoonlight-app
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        echo "Starting puzzle sync..."
        pnpm run sync-puzzles
        echo "Sync command completed"
      
    - name: Verify sync
      run: |
        echo "Puzzle sync completed successfully!"
        echo "Check your Supabase dashboard to verify puzzles were uploaded."
