name: Sync Puzzles to Supabase

on:
  push:
    branches: [ main, master ]
    paths:
      - 'puzzles/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-puzzles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Sync puzzles to Supabase
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        SYNC_SECRET_KEY: ${{ secrets.SYNC_SECRET_KEY }}
      run: |
        # Check if puzzles directory exists and has content
        if [ ! -d "puzzles" ] || [ -z "$(ls -A puzzles)" ]; then
          echo "No puzzles directory or no puzzles found"
          exit 0
        fi
        
        # Call the sync API
        curl -X GET "${{ secrets.VERCEL_URL }}/api/admin/sync-storage?key=${{ secrets.SYNC_SECRET_KEY }}" \
          -H "Content-Type: application/json" \
          --fail-with-body
          
    - name: Verify sync
      run: |
        echo "Puzzle sync completed successfully!"
        echo "Check your Supabase dashboard to verify puzzles were uploaded."
