name: Sync Puzzles to Supabase

on:
  push:
    branches: [ main, master ]
    paths:
      - 'puzzles/**'
      - 'thenoonlight-app/puzzles/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-puzzles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install pnpm
      run: npm install -g pnpm
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'
      
    - name: Debug environment
      run: |
        echo "Current directory: $(pwd)"
        echo "Repository contents:"
        ls -la
        echo "Checking for thenoonlight-app directory:"
        ls -la thenoonlight-app/ || echo "thenoonlight-app directory not found"
        echo "Checking for puzzles directory:"
        ls -la puzzles/ || echo "puzzles directory not found in root"
        ls -la thenoonlight-app/puzzles/ || echo "puzzles directory not found in thenoonlight-app"
      
    - name: Determine working directory
      id: set-dir
      run: |
        if [ -d "thenoonlight-app" ]; then
          echo "working-dir=./thenoonlight-app" >> $GITHUB_OUTPUT
          echo "Found thenoonlight-app directory"
        else
          echo "working-dir=." >> $GITHUB_OUTPUT
          echo "Using root directory"
        fi
      
    - name: Install dependencies
      working-directory: ${{ steps.set-dir.outputs.working-dir }}
      run: pnpm install
      
    - name: List puzzle files
      id: list-puzzles
      run: |
        WORK_DIR="${{ steps.set-dir.outputs.working-dir }}"
        echo "Working directory: $WORK_DIR"
        if [ -d "$WORK_DIR/puzzles" ]; then
          echo "Puzzle files found:"
          find "$WORK_DIR/puzzles" -name "*.json" -o -name "*.zip" | head -20
          echo "Puzzle directories:"
          ls -la "$WORK_DIR/puzzles/"
        else
          echo "No puzzles directory found in $WORK_DIR"
          exit 1
        fi
      
    - name: Validate puzzles
      working-directory: ${{ steps.set-dir.outputs.working-dir }}
      run: pnpm run validate-puzzles
      
    - name: Debug secrets
      run: |
        echo "Checking GitHub secrets availability:"
        echo "- NEXT_PUBLIC_SUPABASE_URL secret exists: $([ -n "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" ] && echo "Yes" || echo "No")"
        echo "- SUPABASE_SERVICE_ROLE_KEY secret exists: $([ -n "${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" ] && echo "Yes" || echo "No")"
        echo "Secret values (first 10 chars):"
        echo "- NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:0:10}..."
        echo "- SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY:0:10}..."
      
    - name: Sync puzzles to Supabase
      working-directory: ${{ steps.set-dir.outputs.working-dir }}
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        echo "Starting puzzle sync from $(pwd)..."
        echo "Environment check:"
        echo "- NEXT_PUBLIC_SUPABASE_URL: $([ -n "$NEXT_PUBLIC_SUPABASE_URL" ] && echo "Set" || echo "Missing")"
        echo "- SUPABASE_SERVICE_ROLE_KEY: $([ -n "$SUPABASE_SERVICE_ROLE_KEY" ] && echo "Set" || echo "Missing")"
        pnpm run sync-puzzles
        echo "Sync command completed"
      
    - name: Verify sync
      run: |
        echo "Puzzle sync completed successfully!"
        echo "Check your Supabase dashboard to verify puzzles were uploaded."
