name: Sync Puzzles to Supabase

on:
  push:
    branches: [ main, master ]
    paths:
      - 'puzzles/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-puzzles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Wait for Vercel deployment
      run: sleep 60
      
    - name: Sync puzzles to Supabase
      env:
        GITHUB_SYNC_KEY: ${{ secrets.GITHUB_SYNC_KEY }}
      run: |
        # Try multiple possible URLs
        POSSIBLE_URLS=(
          "https://${{ github.repository }}.vercel.app"
          "https://${{ github.repository }}-git-main-${{ github.repository_owner }}.vercel.app"
          "https://${{ github.repository }}-${{ github.sha }}.vercel.app"
        )
        
        SYNC_SUCCESS=false
        
        for url in "${POSSIBLE_URLS[@]}"; do
          echo "Trying to sync with: $url"
          
          if curl -X GET "$url/api/admin/sync-storage?key=$GITHUB_SYNC_KEY" \
            -H "Accept: application/json" \
            --max-time 30 \
            --fail-with-body; then
            echo "✅ Successfully synced puzzles with $url"
            SYNC_SUCCESS=true
            break
          else
            echo "❌ Failed to sync with $url"
          fi
        done
        
        if [ "$SYNC_SUCCESS" = false ]; then
          echo "❌ Failed to sync puzzles with any URL"
          exit 1
        fi
