name: Sync Puzzles to Supabase

on:
  push:
    branches: [ main, master ]
    paths:
      - 'puzzles/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  sync-puzzles:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Validate puzzles
      run: npm run validate-puzzles
      
    - name: Sync puzzles to Supabase
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: npm run sync-puzzles
      
    - name: Verify sync
      run: |
        echo "Puzzle sync completed successfully!"
        echo "Check your Supabase dashboard to verify puzzles were uploaded."
